version: '3'

services: 
    db:
        build: ./db
    apparel:
        build: ./apparel
        volumes: 
            - ./apparel:/app
        depends_on: 
            - db
        ports: 
            - 5001:80
            